services:
  - type: web
    name: forgeph-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SALT
        value: 10
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://forge-philippines.windsurf.build
      - key: SOCKET_CORS_ORIGIN
        value: https://forge-philippines.windsurf.build
      - key: ALLOW_ORIGINS
        value: https://forge-philippines.windsurf.build,https://forge-philippines-wz24z.netlify.app
